[workspace]
git_release_enable = false
release_always = false

[[package]]
name = "deepwrite"
publish = false
git_only = true

[[package]]
name = "edtui"
release = false
publish = false
changelog_update = false
